apiVersion: apps/v1
kind: Deployment
metadata:
  name: cors-proxy
spec:
  replicas: 2 # starting point, HPA will change this
  selector:
    matchLabels:
      app: cors-proxy
  template:
    metadata:
      labels:
        app: cors-proxy
    spec:
      containers:
      - name: cors-proxy
        image: rohit17061997/cors-proxy:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
